create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time time, start_time time, title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration bigint, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
create sequence hibernate_sequence start with 1 increment by 1;
create table race (id bigint not null, country varchar(255), end_time varchar(255), start_time varchar(255), title varchar(255), primary key (id));
create table race_result (id bigint not null, race_id bigint, primary key (id));
create table rider (id bigint not null, age integer, duration double, email varchar(255), name varchar(255) not null, race_riders bigint, primary key (id));
alter table race_result add constraint FKko06spjnaxu6pd4f2qucqdg1 foreign key (race_id) references race;
alter table rider add constraint FKc56p3hcqok1heqcd6lvpra0tu foreign key (race_riders) references race_result;
